"""adicionado foreign key à coluna 'created_by' para relação com a tabela 'user'.

Revision ID: 935c87ddf649
Revises: bfc1feb6106f
Create Date: 2025-06-28 10:05:23.297926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '935c87ddf649'
down_revision = 'bfc1feb6106f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_orders_created_by_user', 'user', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
