"""Alterado nome da tabela 'status_type_for_orders' para 'orders_status'. Também, renomeado a coluna 'status_id' para 'order_status_id' da tabela 'orders_status'.

Revision ID: bfc1feb6106f
Revises: e0f5c48669e7
Create Date: 2025-06-28 09:06:15.473931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfc1feb6106f'
down_revision = 'e0f5c48669e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('status_type_for_orders', 'orders_status')
    

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('status_id', new_column_name='order_status_id')
        batch_op.create_foreign_key(
            'fk_orders_order_status_id',
            'orders_status',
            ['order_status_id'],
            ['id']
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'status_type_for_orders', ['status_id'], ['id'])
        batch_op.drop_column('order_status_id')
        
    op.rename_table('orders_status', 'status_type_for_orders')
    # ### end Alembic commands ###
