"""Adicionado email_hash, para consultas de login.

Revision ID: dbfc51cb11f4
Revises: 95d9b3118584
Create Date: 2025-06-23 03:27:27.338437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbfc51cb11f4'
down_revision = '95d9b3118584'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_hash', sa.String(), nullable=False))
        batch_op.create_unique_constraint('uq_user_email_hash', ['email_hash'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email_hash')

    # ### end Alembic commands ###
